import eslint from '@eslint/js'
import tseslint from '@typescript-eslint/eslint-plugin'
import tsparser from '@typescript-eslint/parser'
import vue from 'eslint-plugin-vue'
import vueParser from 'vue-eslint-parser'
import vuejsAccessibility from 'eslint-plugin-vuejs-accessibility'
import globals from 'globals'

export default [
  eslint.configs.recommended,
  {
    ignores: [
      'dist/**',
      'node_modules/**',
      'coverage/**',
      '*.config.js',
      '*.config.ts',
      // Generated by `npm run generate:api-types`; check:api-types diffs it
      // against a fresh generation, so --fix must not touch it.
      'src/api/generated/schema.ts',
    ],
  },
  // TypeScript files
  {
    files: ['**/*.ts', '**/*.tsx'],
    languageOptions: {
      parser: tsparser,
      parserOptions: {
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        ...globals.browser,
        ...globals.node,
      },
    },
    plugins: {
      '@typescript-eslint': tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      // `any` is a type-safety hole — treat it as an error in new TS code.
      // Scoped overrides below allow it where the surrounding ecosystem
      // (test mocks, PrimeVue wrapper passthroughs) legitimately needs it.
      '@typescript-eslint/no-explicit-any': 'error',
      '@typescript-eslint/explicit-function-return-type': 'off',
      'no-unused-vars': 'off', // Use @typescript-eslint/no-unused-vars instead
      'no-undef': 'off', // TypeScript handles this
      // i18n: forbid raw zero-arg .toLocale*() calls. They default to the
      // system locale, which bypasses our Pinia locale store and prevents
      // `es`/pseudo/any non-default locale from taking effect. Use the
      // useFormatters() composable (src/composables/useFormatters.ts) or
      // pass an explicit locale argument. See
      // docs/architecture/adr/0001-i18n-strategy.md.
      'no-restricted-syntax': [
        'error',
        {
          selector: "CallExpression[callee.type='MemberExpression'][callee.property.name='toLocaleString'][arguments.length=0]",
          message: 'Do not call .toLocaleString() without a locale argument — use useFormatters() from @/composables/useFormatters so locale changes propagate.',
        },
        {
          selector: "CallExpression[callee.type='MemberExpression'][callee.property.name='toLocaleDateString'][arguments.length=0]",
          message: 'Do not call .toLocaleDateString() without a locale argument — use useFormatters() from @/composables/useFormatters so locale changes propagate.',
        },
        {
          selector: "CallExpression[callee.type='MemberExpression'][callee.property.name='toLocaleTimeString'][arguments.length=0]",
          message: 'Do not call .toLocaleTimeString() without a locale argument — use useFormatters() from @/composables/useFormatters so locale changes propagate.',
        },
      ],
    },
  },
  // Vue files
  {
    files: ['**/*.vue'],
    languageOptions: {
      parser: vueParser,
      parserOptions: {
        parser: tsparser,
        ecmaVersion: 'latest',
        sourceType: 'module',
      },
      globals: {
        ...globals.browser,
      },
    },
    plugins: {
      vue,
      '@typescript-eslint': tseslint,
      'vuejs-accessibility': vuejsAccessibility,
    },
    rules: {
      ...vue.configs['vue3-recommended'].rules,
      // Starter a11y ruleset. These are the rules we can confidently turn
      // on without a sweeping codebase audit — they catch concrete,
      // well-defined a11y regressions. A broader pass (heading levels,
      // focus order, landmark uniqueness) is tracked in
      // docs/accessibility/action-plan.md.
      // Starter a11y gate. Enforced as `error`: the objective,
      // low-false-positive rules that genuinely protect users. Turned
      // `off`: rules that produce mostly PrimeVue-wrapper false positives
      // (form-control-has-label doesn't see the associated <label>
      // when the input is inside a custom component); the action plan in
      // docs/accessibility/ tracks those as manual audit items.
      'vuejs-accessibility/alt-text': 'error',
      'vuejs-accessibility/anchor-has-content': 'error',
      'vuejs-accessibility/aria-props': 'error',
      'vuejs-accessibility/aria-role': 'error',
      'vuejs-accessibility/aria-unsupported-elements': 'error',
      'vuejs-accessibility/heading-has-content': 'error',
      'vuejs-accessibility/iframe-has-title': 'error',
      'vuejs-accessibility/no-access-key': 'error',
      'vuejs-accessibility/no-autofocus': 'error',
      'vuejs-accessibility/no-distracting-elements': 'error',
      'vuejs-accessibility/no-redundant-roles': 'error',
      'vuejs-accessibility/role-has-required-aria-props': 'error',
      'vuejs-accessibility/tabindex-no-positive': 'error',
      // click-events-have-key-events: interactive <div>/<span> handlers
      // must have keyboard equivalents. Flipped on after a sweep that
      // fixed 7 violations. Ongoing: any new clickable non-button needs
      // @keydown + tabindex or an eslint-disable with justification.
      'vuejs-accessibility/click-events-have-key-events': 'error',
      'vuejs-accessibility/form-control-has-label': 'error',
      // interactive-supports-focus: currently no violations; gated to
      // prevent regressions.
      'vuejs-accessibility/interactive-supports-focus': 'error',
      // label-has-for: requires explicit for/id association. ~180 sites
      // currently use sibling labels or aria-label; flipping this would
      // churn every form without user-visible a11y change (SR users
      // already get the label via aria-label). Tracked in
      // docs/accessibility/action-plan.md.
      'vuejs-accessibility/label-has-for': 'off',
      // mouse-events-have-key-events: no current violations; gated to
      // prevent regressions.
      'vuejs-accessibility/mouse-events-have-key-events': 'error',
      // no-onchange: the rule recommends @blur over @change for form
      // controls, but that's semantically wrong for <select>/<Select>
      // dropdowns — @change fires when the user picks a new option,
      // while @blur fires on every focus-out regardless. All four
      // current sites are dropdown filters (Theme, Role, Status,
      // Feedback type) that correctly use @change. Keeping this rule
      // `off` rather than blanket-suppressing every <select>.
      'vuejs-accessibility/no-onchange': 'off',
      'vue/multi-word-component-names': 'off',
      // v-html is used only for Markdown content that goes through
      // renderMarkdown() -> DOMPurify.sanitize(). Coverage is enforced by
      // InstructionsPanel.test.ts (XSS-vector test suite). New v-html sites
      // should not be added — reviewers catch that in PR review.
      'vue/no-v-html': 'off',
      'vue/require-default-prop': 'off',
      'vue/attributes-order': 'off', // Too opinionated for existing codebase
      '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
      // Also enforce no-explicit-any inside <script setup> blocks. Previously
      // this rule was only applied to .ts files, which let the console
      // components accumulate untyped RFB/SPICE handles unchecked.
      '@typescript-eslint/no-explicit-any': 'error',
      'no-unused-vars': 'off', // Use @typescript-eslint/no-unused-vars instead
      'no-undef': 'off', // TypeScript handles this
      // i18n: same raw-.toLocale*() gate as the TS block. See comment there.
      'no-restricted-syntax': [
        'error',
        {
          selector: "CallExpression[callee.type='MemberExpression'][callee.property.name='toLocaleString'][arguments.length=0]",
          message: 'Do not call .toLocaleString() without a locale argument — use useFormatters() from @/composables/useFormatters so locale changes propagate.',
        },
        {
          selector: "CallExpression[callee.type='MemberExpression'][callee.property.name='toLocaleDateString'][arguments.length=0]",
          message: 'Do not call .toLocaleDateString() without a locale argument — use useFormatters() from @/composables/useFormatters so locale changes propagate.',
        },
        {
          selector: "CallExpression[callee.type='MemberExpression'][callee.property.name='toLocaleTimeString'][arguments.length=0]",
          message: 'Do not call .toLocaleTimeString() without a locale argument — use useFormatters() from @/composables/useFormatters so locale changes propagate.',
        },
      ],
    },
  },
  // Overrides: test files legitimately mock with `any`.
  {
    files: ['**/*.test.ts', '**/*.spec.ts'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
    },
  },
  // Overrides: PrimeVue Volt wrappers pass through PrimeVue's own loosely-typed
  // props. Typing these properly requires upstream PrimeVue generic changes
  // that are out of scope; keep `any` allowed here rather than silencing
  // per-line with eslint-disable comments. Same reasoning applies to the
  // autofocus prop: PrimeVue's Dialog/ConfirmDialog/Drawer accept it as a
  // configurable passthrough, and removing it would change the component's
  // public API. Consumers who want to avoid autofocus simply don't set it.
  {
    files: ['src/components/volt/**/*.{ts,tsx,vue}'],
    rules: {
      '@typescript-eslint/no-explicit-any': 'off',
      'vuejs-accessibility/no-autofocus': 'off',
      // Volt wrappers don't own labels — consumers apply them. The rule
      // flags the wrapper's internal <Select>/<Textarea>/<InputText>
      // tags but the a11y responsibility is at the call site.
      'vuejs-accessibility/form-control-has-label': 'off',
    },
  },
  // NOTE: The previous `src/components/console/**` blanket override for
  // @typescript-eslint/no-explicit-any was removed in Phase 2. The VNC/SPICE
  // console components now use the local `types/novnc.d.ts` and
  // `types/spice-html5.d.ts` shims — `any` is no longer required for vendor
  // handles or event callbacks. Any future need for `any` in this directory
  // should be scoped to a single file or line with an eslint-disable comment
  // that explains why, rather than re-broadening the rule.
  // Test files
  {
    files: ['**/*.test.ts', '**/*.spec.ts'],
    languageOptions: {
      globals: {
        ...globals.browser,
        ...globals.node,
        vi: 'readonly',
        describe: 'readonly',
        it: 'readonly',
        expect: 'readonly',
        beforeEach: 'readonly',
        afterEach: 'readonly',
        beforeAll: 'readonly',
        afterAll: 'readonly',
      },
    },
  },
]
